name: artifacts

on: [push]

env:
  FILE_NAME: hello
  FILE_PATH: resources/hello.go

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
        run: go build ${{ env.FILE_PATH }}

      - name: Build ${{ env.FILE_NAME }} for windows-latest
        run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_PATH }}

      - name: List files
        run: ls -al

      - name: Upload artifact for linux
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

      - name: Upload artifact for windows
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: windows

      - name: Test ${{ env.FILE_NAME }}
        run: windows/${{ env.FILE_NAME }}.exe

  test-linux:
    name: Test Windows
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: linux

      - name: Test ${{ env.FILE_NAME }}
        run: ./linux/${{ env.FILE_NAME }}
